### ISSUE TITLE
Linkin error while compiling my own application

### ISSUE THREAD

**Issue by Jamaslab** [youbot/youbot_applications#3]
Hello,
when I try to compile my own application I get the following error

[ 14%] Building CXX object CMakeFiles/bin/youbot_slam.dir/test/youbot_slam.cpp.o
In file included from /usr/local/include/youbot/youbot/youbot/YouBotSlaveMsg.hpp:56:0,
                 from /usr/local/include/youbot/youbot/youbot/YouBotJointParameterReadOnly.hpp:62,
                 from /usr/local/include/youbot/youbot/youbot/YouBotJointParameter.hpp:62,
                 from /usr/local/include/youbot/youbot/youbot/YouBotJoint.hpp:67,
                 from /usr/local/include/youbot/youbot/youbot/YouBotBase.hpp:62,
                 from /home/youbot/applications/cslam/include/YouBot.h:5,
                 from /home/youbot/applications/cslam/test/youbot_slam.cpp:1:
/usr/local/include/youbot/youbot/src/ethercattype.h:67:0: warning: "TRUE" redefined [enabled by default]
/usr/local/include/json-c/json_object.h:21:0: note: this is the location of the previous definition
/usr/local/include/youbot/youbot/src/ethercattype.h:68:0: warning: "FALSE" redefined [enabled by default]
/usr/local/include/json-c/json_object.h:18:0: note: this is the location of the previous definition
In file included from /usr/include/c++/4.6/bits/locale_facets_nonio.h:1936:0,
                 from /usr/include/c++/4.6/locale:43,
                 from /usr/include/c++/4.6/iomanip:45,
                 from /usr/include/boost/date_time/date_formatting.hpp:16,
                 from /usr/include/boost/date_time/gregorian/formatters.hpp:17,
                 from /usr/include/boost/date_time/gregorian/gregorian.hpp:25,
                 from /usr/include/boost/date_time/posix_time/time_formatters.hpp:12,
                 from /usr/include/boost/date_time/posix_time/posix_time.hpp:24,
                 from /usr/local/include/youbot/youbot/generic/Logger.hpp:57,
                 from /usr/local/include/youbot/youbot/youbot/YouBotBase.hpp:57,
                 from /home/youbot/applications/cslam/include/YouBot.h:5,
                 from /home/youbot/applications/cslam/test/youbot_slam.cpp:1:
/usr/include/c++/4.6/bits/locale_facets_nonio.tcc: In member function ‘_InIter std::time_get<_CharT, _InIter>::_M_extract_name(std::time_get<_CharT, _InIter>::iter_type, std::time_get<_CharT, _InIter>::iter_type, int&, const _CharT*_, std::size_t, std::ios_base&, std::ios_base::iostate&) const’:
/usr/include/c++/4.6/bits/locale_facets_nonio.tcc:918:22: error: expected unqualified-id before ‘(’ token
In file included from /usr/local/include/youbot/youbot/youbot/YouBotSlaveMsg.hpp:56:0,
                 from /usr/local/include/youbot/youbot/youbot/YouBotJointParameterReadOnly.hpp:62,
                 from /usr/local/include/youbot/youbot/youbot/YouBotJointParameter.hpp:62,
                 from /usr/local/include/youbot/youbot/youbot/YouBotJoint.hpp:67,
                 from /usr/local/include/youbot/youbot/youbot/YouBotBase.hpp:62,
                 from /home/youbot/applications/cslam/include/YouBot.h:5,
                 from /home/youbot/applications/cslam/test/youbot_slam.cpp:1:
/usr/local/include/youbot/youbot/src/ethercattype.h: At global scope:
/usr/local/include/youbot/youbot/src/ethercattype.h:66:29: error: conflicting declaration ‘typedef unsigned char boolean’
/usr/local/include/json-c/json_object.h:28:13: error: ‘boolean’ has a previous declaration as ‘typedef int boolean’
make[2]: *_\* [CMakeFiles/bin/youbot_slam.dir/test/youbot_slam.cpp.o] Error 1
make[1]: **\* [CMakeFiles/bin/youbot_slam.dir/all] Error 2
make: **\* [all] Error 2

Can someone help me?
Thank you
Giacomo

**Comment by wnowak** [comment]
These errors come from including the youbot_driver headers, so the issue would rather belong to that repository.

I have no idea for the first error in locale_facets_nonio.tcc:. This comes due to the line
#include "boost/date_time/posix_time/posix_time.hpp"
in youbot driver's Logger.hpp file.
Maybe you can try out this line as the first line in your youbot_slam.cpp file, and see if the error persists. If yes, it is some strange thing with boost date_time...

The second error comes from combining old versions of youbot driver and json-c libraries, who both defined a boolean type. For json-c there was a patch solving this:
https://github.com/json-c/json-c/commit/37e74674769d2ae224ad52b1a866eb38c00e2821

Errors as: ‘quantity’ in namespace ‘youbot’ does not name a type
lack the boost namespace. just replace quantity with boost::units::quantity.

Can you try a newer version of json-c? 
Which Ubuntu version are you using?

Walter

**Comment by Jamaslab** [comment]
I'm using Ubuntu 12.04, with the preinstalled drivers. I bought the youbot a couple of weeks ago, and I didn't change anything, just trying to implement a controller for my SLAM system.

**Comment by Jamaslab** [comment]
Ok, solved. The json's warnings persist, but there are no more error. I just included 
#include "boost/date_time/posix_time/posix_time.hpp"
at the top of the file.

Thank you
Giacomo
